### ISSUE TITLE
RTU mode: exception popup

### ISSUE THREAD

**Issue by diggit** [ed-chemnitz/qmodbus#13]
Every time, exception message is received, popup window about this exception appears. This behavior is  annoying when I try to debug/fiddle with some device. Is there any way to suppress this popup window?

**Comment by tobydox** [comment]
Currently not but should be easy to implement. Do you want to try to code it?

**Comment by diggit** [comment]
I'd spend too much time of code reading and understanding. It should be done by someone familiar with qmodbus code.

There is another thing. Exceptions are "normal" frames. They should be handled as responses. In current state, you don't know if exception reply checksum is ok. Request gets marked as exceptioned and that is all.

**Comment by tobydox** [comment]
This has been fixed through #16
