### ISSUE TITLE
Windows builds are very old

### ISSUE THREAD

**Issue by shiftee** [ed-chemnitz/qmodbus#21]
The windows builds downloadable from Sourceforge are a few years out of date.

They are missing large new features such as ModbusTCP.

Would it be possible to provide binaries of the master branch (doing a release if necessary)?

Thanks

**Comment by tobydox** [comment]
Thanks for your feedback! I just released version 0.3.0 and uploaded a 64 bit build for Windows - hope it works for you :-)

**Comment by cheak1974** [comment]
Sorry for waking up this issue, but I can't find the 0.3 on sourceforge. The last version available there is 0.21 https://sourceforge.net/projects/qmodbus/files/qmodbus/

Can you please provide a link to 0.30? Thank you very much in advance.

**Comment by ragreenburg** [comment]
@cheak1974 This is old but in case anyone else finds this and wants the newest version (0.3 at the moment) it is [here](https://github.com/ed-chemnitz/qmodbus/releases).
