### ISSUE TITLE
Modbus TCP: Write Multiple Registers

### ISSUE THREAD

**Issue by samweisgamdschie** [ed-chemnitz/qmodbus#35]
Hello!

I am trying to send a Write Multiple Registers request with qmodbus to a Modbus TCP Server but there is no input field for the data. 

![grafik](https://user-images.githubusercontent.com/3033598/134036792-8be7b693-5f1d-49b0-a8b4-5b238014ffe6.png)

Reading multiple registers is possible, but when I want to write to the same holding registers only sending zero's is possible.
![grafik](https://user-images.githubusercontent.com/3033598/134036927-4fe9dcbc-9ff6-498f-b8f7-77951d56405c.png)

I am using qmodbus 0.3.0 with opensuse tumbleweed.

Any help in setting specific (maybe hex values) for writing registers is appreciated.

**Comment by shiftee** [comment]
You use the **Data** column in the **Registers** section.
Click the cell, enter the desired value, hit send

**Comment by samweisgamdschie** [comment]
Many Thanks, it worked this way!
